spring:
  datasource:
    url: jdbc:h2:mem:jdbc-home-work
  messages:
    basename: "i18n/messages"

  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true

default:
  parameter:
    locale: ru
