DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRE;

CREATE TABLE GENRE(ID BIGINT PRIMARY KEY AUTO_INCREMENT, GENRE_NAME VARCHAR(255));
CREATE TABLE AUTHOR(ID BIGINT PRIMARY KEY AUTO_INCREMENT, AUTHOR_NAME VARCHAR(255));
CREATE TABLE BOOK(ID BIGINT PRIMARY KEY AUTO_INCREMENT, BOOK_NAME VARCHAR(255), AUTHOR_ID BIGINT, GENRE_ID BIGINT);

ALTER TABLE BOOK ADD FOREIGN KEY (GENRE_ID) REFERENCES GENRE(ID);
ALTER TABLE BOOK ADD FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID);
