spring:
  batch:
    job:
      enabled: false
  shell:
    interactive:
      enabled: true

  datasource:
    url: jdbc:h2:mem:jpa-home-work
  sql:
    init:
      mode: always

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    mongodb:
      database: library

mongock:
  runner-type: "ApplicationRunner" # default
  #  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.spring.batch.changelog
