DROP TABLE IF EXISTS BOOK_AUTHOR;
DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS AUTHOR;
DROP TABLE IF EXISTS GENRE;

CREATE TABLE GENRE(ID BIGINT PRIMARY KEY AUTO_INCREMENT, GENRE_NAME VARCHAR(255), MONGO_ID VARCHAR(100));
CREATE TABLE AUTHOR(ID BIGINT PRIMARY KEY AUTO_INCREMENT, AUTHOR_NAME VARCHAR(255), MONGO_ID VARCHAR(100));

CREATE TABLE BOOK(ID BIGINT PRIMARY KEY AUTO_INCREMENT, BOOK_NAME VARCHAR(255), GENRE_ID BIGINT, MONGO_ID VARCHAR(100));
ALTER TABLE BOOK ADD FOREIGN KEY (GENRE_ID) REFERENCES GENRE(ID);

CREATE TABLE BOOK_AUTHOR(ID BIGINT PRIMARY KEY AUTO_INCREMENT, BOOK_ID BIGINT, AUTHOR_ID BIGINT);
ALTER TABLE BOOK_AUTHOR ADD FOREIGN KEY (BOOK_ID) REFERENCES BOOK(ID);
ALTER TABLE BOOK_AUTHOR ADD FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID);
