INSERT INTO GENRE (GENRE_NAME) VALUES ('GENRE 1');
INSERT INTO GENRE (GENRE_NAME) VALUES ('GENRE 2');
INSERT INTO AUTHOR (AUTHOR_NAME) VALUES ('AUTHOR 1');
INSERT INTO AUTHOR (AUTHOR_NAME) VALUES ('AUTHOR 2');

INSERT INTO BOOK (BOOK_NAME, GENRE_ID) VALUES ('BOOK 1', 1);
INSERT INTO BOOK_AUTHOR (BOOK_ID, AUTHOR_ID) VALUES (1, 1);
INSERT INTO BOOK_AUTHOR (BOOK_ID, AUTHOR_ID) VALUES (1, 2);

INSERT INTO BOOK (BOOK_NAME, GENRE_ID) VALUES ('BOOK 2', 2);
INSERT INTO BOOK_AUTHOR (BOOK_ID, AUTHOR_ID) VALUES (2, 2);

INSERT INTO COMMENT (COMMENT_TXT, BOOK_ID) VALUES ('COMMENT 1', 1);
INSERT INTO COMMENT (COMMENT_TXT, BOOK_ID) VALUES ('COMMENT 2', 2);