INSERT INTO GENRE (GENRE_NAME) VALUES ('GENRE 1');
INSERT INTO GENRE (GENRE_NAME) VALUES ('GENRE 2');
INSERT INTO AUTHOR (AUTHOR_NAME) VALUES ('AUTHOR 1');
INSERT INTO AUTHOR (AUTHOR_NAME) VALUES ('AUTHOR 2');

INSERT INTO BOOK (BOOK_NAME, AUTHOR_ID, GENRE_ID) VALUES ('BOOK 1', 1, 1);
