spring:

  datasource:
    url: jdbc:h2:mem:jpa-home-work

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
  sql:
    init:
      mode: always
      data-locations: import.sql


