spring:

  datasource:
    url: jdbc:h2:mem:jpa-home-work
    initialization-mode: always
#    data: import.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
#    defer-datasource-initialization: true

  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true

#вызвать http://localhost:8080/actuator для получения метрик
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    logfile:
      enabled: true
  health:
    defaults:
      enabled: true

logging:
  level:
    root: info
    ru.otus: info
  file:
    name: integration.log

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10 # количество вызовов, которые следует учитывать при включении автоматического выключателя
      minimumNumberOfCalls: 3 # минимальное необходимое количество вызовов, перед которым автоматический выключатель может рассчитать частоту ошибок
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 5s # Продолжительность, в течение которой автоматический выключатель должен оставаться в разомкнутом состоянии перед переходом в полуоткрытое состояние
      failureRateThreshold: 50 # настраивает порог частоты отказов в процентах. Если x процентов вызовов не работают, выключатель отключается
      eventConsumerBufferSize: 10
      slowCallRateThreshold: 65 # настраивает порог низкой скорости вызова в процентах. Если x процентов вызовов являются медленными, автоматический выключатель отключается
      slowCallDurationThreshold: 2s # настраивает порог продолжительности времени, при котором вызовы считаются медленными
      recordExceptions:
        - java.util.concurrent.TimeoutException
      #ignoreException — настроить исключение, которое автоматический выключатель может игнорировать и не будет учитываться при успешном или неудачном вызове удаленного сервиса.
  instances:
    integration:
      baseConfig: default

