INSERT INTO PEOPLE (PEOPLE_NAME, SEX, SEND_MAIL, SEND_PUSH_MESSAGE, SEND_SMS)
        VALUES ('USER 1', 'M', 1, 1, 0);
INSERT INTO PEOPLE (PEOPLE_NAME, SEX, SEND_MAIL, SEND_PUSH_MESSAGE, SEND_SMS)
VALUES ('USER 2', 'W', 0, 1, 1);